{% set version = "1.1.0" %}
{% set ixmp_version = "0.1.3" %}
{% set sha256 = "7dec36641094420851fd46966110c271aceecb822e3f874bd7c0538a2274c54e" %}

package:
  name: message-ix
  version: {{ version }}

source:
  url: https://github.com/iiasa/message_ix/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - messageix-config=message_ix.cli:config
    - messageix-dl=message_ix.cli:dl

requirements:
  build:
    - python
    - pip
  run:
    - ixmp =={{ ixmp_version }}

test:
  imports:
    - message_ix
  commands:
    - messageix-config -h
    - messageix-dl -h
    - python -c "import ixmp; print(ixmp.__version__); assert ixmp.__version__ == '{{ ixmp_version }}'"
    - python -c "import message_ix; print(message_ix.__version__); assert message_ix.__version__ == '{{ version }}'"
    - python -c "import ixmp; import message_ix; ixmp.Platform(dbtype='HSQLDB')"
    - messageix-dl --repo_path tutorial

about:
  home: https://github.com/iiasa/message_ix
  license: Apache-2.0
  license_file: LICENSE
  summary: 'The integrated assessment and energy systems model MESSAGEix https://MESSAGEix.iiasa.ac.at/'

extra:
  recipe-maintainers:
    - gidden
