{% set name = "message-ix" %}
{% set name_ = "message_ix" %}
{% set version = "3.5.0" %}
{% set hash = "792d396a9a2be748a5be19f0256ab327740ac832f7a9b75dcdba26e3af7d8917" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name_ }}/{{ name_ }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - message-ix=message_ix.cli:main

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools-scm

  run:
    - python >=3.7
    # Install requirements
    - click
    - ixmp >=3.5.0
    - numpy
    - pandas >=1.2
    # Extra requirements
    - iam-units
    - jupyter
    - matplotlib-base
    - pint
    - plotnine
    - pyam >=0.6

test:
  imports:
    - message_ix
  requires:
    - asyncssh
    - requests
  commands:
  # General CLI usage
    - message-ix --help
    - message-ix add-years --help
    - message-ix nightly --help
    - message-ix show-versions
  # Download the tutorials
    - message-ix dl tutorial

about:
  home: https://github.com/iiasa/message_ix
  license: Apache-2.0
  license_file: LICENSE
  summary: The MESSAGE integrated assessment and energy systems model

extra:
  recipe-maintainers:
    - gidden
    - khaeru
    - LauWien
