{% set name = "message-ix" %}
{% set name_ = "message_ix" %}
{% set version = "3.11.0" %}
{% set hash = "bcb36c2e93c783031ad02293fbe5ff795195b2ac5e463e5373321e86087989ec" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name_ }}/{{ name_ }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - message-ix=message_ix.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    # Install requirements
    - click
    - genno >=1.20
    - importlib-metadata
    - ixmp >=3.11
    - numpy
    - pandas >=1.2
    # Extra requirements
    - iam-units
    - jupyter
    - matplotlib-base
    - pint
    - plotnine
    - pyam >=0.6

test:
  imports:
    - message_ix
  requires:
    - requests
    - python {{ python_min }}
  commands:
  # General CLI usage
    - message-ix --help
    - message-ix add-years --help
    - message-ix show-versions
  # Download the tutorials
    - message-ix dl tutorial

about:
  home: https://github.com/iiasa/message_ix
  license: Apache-2.0
  license_file: LICENSE
  summary: The MESSAGE integrated assessment and energy systems model

extra:
  recipe-maintainers:
    - khaeru
    - glatterf42
