{% set name = "message-ix" %}
{% set name_ = "message_ix" %}
{% set version = "3.8.0" %}
{% set hash = "d015a7c35e333ff8cc3d16fec42d04339cd36d6d35d5404d833585252cae88c8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name_ }}/{{ name_ }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - message-ix=message_ix.cli:main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    # Install requirements
    - click
    - genno
    - importlib_metadata
    - ixmp >=3.8.0
    - numpy
    - pandas >=1.2
    # Extra requirements
    - iam-units
    - jupyter
    - matplotlib-base
    - pint
    - plotnine
    - pyam >=0.6

test:
  imports:
    - message_ix
  requires:
    - asyncssh
    - requests
  commands:
  # General CLI usage
    - message-ix --help
    - message-ix add-years --help
    - message-ix nightly --help
    - message-ix show-versions
  # Download the tutorials
    - message-ix dl tutorial

about:
  home: https://github.com/iiasa/message_ix
  license: Apache-2.0
  license_file: LICENSE
  summary: The MESSAGE integrated assessment and energy systems model

extra:
  recipe-maintainers:
    - gidden
    - khaeru
    - glatterf42
