{% set name = "message-ix" %}
{% set name_ = "message_ix" %}
{% set version = "3.0.1" %}
{% set hash = "48db07fdd6692b60cb121490ca6bd2affcef4380b9c9fa1c531c46414e53cfba" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name_ }}/{{ name_ }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
  - message-ix=message_ix.cli:main

requirements:
  build:
  - python
  - pip
  - setuptools-scm
  run:
  - ixmp ==3.0.0

test:
  imports:
  - message_ix
  requires:
  - asyncssh
  - requests
  commands:
  # General CLI help
  - message-ix --help
  # Download the tutorials
  - message-ix dl tutorial
  # Special CLI commands loaded from modules
  - message-ix add-years --help
  - message-ix nightly --help

about:
  home: https://github.com/iiasa/message_ix
  license: Apache-2.0
  license_file: LICENSE
  summary: The MESSAGE integrated assessment and energy systems model

extra:
  recipe-maintainers:
  - gidden
  - khaeru
