{% set name = "message-ix" %}
{% set name_ = "message_ix" %}
{% set version = "3.2.0" %}
{% set hash = "c697223f06f64832f0de5cc48a3be36489ab69601c920dec374c0da25083efbe" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name_ }}/{{ name_ }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - message-ix=message_ix.cli:main

requirements:
  build:
    - python >=3.6
    - pip
    - setuptools-scm
  run:
    - python >=3.6
    # Install requirements
    - click
    - ixmp >=3.2.0
    - numpy
    - pandas
    # Extra requirements
    - iam-units
    - jupyter
    - matplotlib-base
    - plotnine
    - pyam >=0.6

test:
  imports:
    - message_ix
  requires:
    - asyncssh
    - requests
  commands:
  # General CLI usage
    - message-ix --help
    - message-ix add-years --help
    - message-ix nightly --help
    - message-ix show-versions
  # Download the tutorials
    - message-ix dl tutorial

about:
  home: https://github.com/iiasa/message_ix
  license: Apache-2.0
  license_file: LICENSE
  summary: The MESSAGE integrated assessment and energy systems model

extra:
  recipe-maintainers:
    - gidden
    - khaeru
